### ISSUE TITLE
Api for SMS credits

### ISSUE THREAD

**Issue by fhsctv** [cmdotcom/text-postman#3]
Hello!

Your company has bought smstrade.de.
This had an API that allowed us to automatically monitor how much SMS credit is available.

It looked like this: https://gateway.smstrade.de/credits/?key=xxxxxxx-xxxxxxxxx-xxxxxx...

We would like to be able to continue monitoring this.
Is there a successor api for this?

Thank you for your efforts.

**Comment by joepb** [comment]
Hi @fhsctv ,

Thanks for your question.
Unfortunately we do not have a similar API available at this time. Our current credit system is more complex than the SMS Trade counterpart because of the many products we provide.

When logged in, an email notification can be set up in your settings, which will notify you when your credit drops below a certain threshold (I'm not sure from the top of my head which that is).

If continuity is paramount for you, it's best to reach out to our sales department and discuss a post-paid account. If you want us to have someone contact you, please feel free to reach out.

Best,

@joepb

**Comment by fhsctv** [comment]
Hi @joepb,

thank you for your answer.
We use that email notification.

Best,

@fhsctv
